#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : | 
                               Nicolae Cleju,
                               ETTI, TUIASI
                                
                             # The title of the book. Will be placed in the left navbar.
author                      : Nicolae Cleju  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : Poza.png  # A path to the book logo
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : false

# Information about where the book exists on the web
repository:
  url                       : https://github.com/nikcleju/Didactic  # Online location of your book
  #path_to_book             : .       # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe        : true

#===================================

# Nic:
# parse:
#   myst_enable_extensions:
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default!
#     - amsmath

sphinx:
  extra_extensions:
    - sphinx_proof
